[package]
name = "attendsys"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.10.1"
openzeppelin = "1.0.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib.git" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.41.0", exclude = ["trace_info", "addition", "fibonacci", "hello_workspaces"] }
assert_macros = "2.8.5"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"


