name: Build

on: [push, pull_request]

env:
  SCARB_VERSION: 2.10.1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.10.1"
          
      - name: Build cairo programs
        run: scarb build
